{"name": "test_invalid_user[invalid_user]", "status": "passed", "description": "Test login with invalid usernames", "steps": [{"name": "Attempting login with invalid user: invalid_user", "status": "passed", "start": 1738274274046, "stop": 1738274277384}, {"name": "Verify login fails with an error message", "status": "passed", "start": 1738274277384, "stop": 1738274277414}], "parameters": [{"name": "username", "value": "'invalid_user'"}], "start": 1738274274046, "stop": 1738274277415, "uuid": "809c79ee-972b-4c5e-8a81-90904d7ebe8f", "historyId": "6daa25dd89334a567a65f07bb1709a08", "testCaseId": "4f31e914b3085cb5cbe97cf962d7ddf3", "fullName": "tests.test_login#test_invalid_user", "labels": [{"name": "story", "value": "Invalid Login Scenarios"}, {"name": "feature", "value": "Login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Ram"}, {"name": "thread", "value": "27844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}