{"name": "test_invalid_user[test_user]", "status": "passed", "description": "Test login with invalid usernames", "steps": [{"name": "Attempting login with invalid user: test_user", "status": "passed", "start": 1738274286075, "stop": 1738274289398}, {"name": "Verify login fails with an error message", "status": "passed", "start": 1738274289398, "stop": 1738274289422}], "parameters": [{"name": "username", "value": "'test_user'"}], "start": 1738274286075, "stop": 1738274289422, "uuid": "04372875-0307-41b7-b6fe-790a2ec07ef1", "historyId": "c1af6456e5777dc06d883438ad103fd8", "testCaseId": "4f31e914b3085cb5cbe97cf962d7ddf3", "fullName": "tests.test_login#test_invalid_user", "labels": [{"name": "story", "value": "Invalid Login Scenarios"}, {"name": "feature", "value": "Login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Ram"}, {"name": "thread", "value": "27844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}