{"name": "test_invalid_user[random_user]", "status": "passed", "description": "Test login with invalid usernames", "steps": [{"name": "Attempting login with invalid user: random_user", "status": "passed", "start": 1738274298687, "stop": 1738274302031}, {"name": "Verify login fails with an error message", "status": "passed", "start": 1738274302031, "stop": 1738274302056}], "parameters": [{"name": "username", "value": "'random_user'"}], "start": 1738274298687, "stop": 1738274302057, "uuid": "9ab2204e-40c2-472c-a286-cc86ce2d7fcc", "historyId": "2528e51a87bf8a26ecb1d78e7fe017de", "testCaseId": "4f31e914b3085cb5cbe97cf962d7ddf3", "fullName": "tests.test_login#test_invalid_user", "labels": [{"name": "story", "value": "Invalid Login Scenarios"}, {"name": "feature", "value": "Login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Ram"}, {"name": "thread", "value": "27844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}